<?php
/**
 * Plugin Name: Hebrew Dates Admin
 * Plugin URI: https://github.com/pauljacobson/hebrew-dates-wp-admin
 * Description: Displays the current Hebrew date in a WordPress Admin dashboard widget and a Gutenberg block, featuring both Hebrew characters and transliteration, plus Jewish holidays and events.
 * Version: 1.1.0
 * Author: Paul Jacobson
 * License: GPL-2.0+
 * License URI: http://www.gnu.org/licenses/gpl-2.0.txt
 * Text Domain: hebrew-dates-admin
 * Requires at least: 6.0
 * Requires PHP: 8.0
 *
 * @package Hebrew_Dates_Admin
 */

// Prevent direct file access.
// This is a security measure to ensure the file is only executed
// within the WordPress environment, not accessed directly via URL.
if ( ! defined( 'ABSPATH' ) ) {
	exit;
}

/**
 * Plugin version constant.
 * Used for cache busting and version tracking.
 */
define( 'HEBREW_DATES_ADMIN_VERSION', '1.1.0' );

/**
 * Plugin directory path constant.
 * Used for including files relative to the plugin directory.
 */
define( 'HEBREW_DATES_ADMIN_PATH', plugin_dir_path( __FILE__ ) );

/**
 * Include the Hebcal API class.
 *
 * This class handles all communication with the Hebcal REST API,
 * including caching responses in WordPress transients.
 */
require_once HEBREW_DATES_ADMIN_PATH . 'includes/class-hebcal-api.php';

/**
 * Enqueue widget styles on the dashboard page.
 *
 * Uses 'admin_enqueue_scripts' with a page check to load the
 * stylesheet only on the main dashboard (index.php), avoiding
 * unnecessary CSS on other admin pages.
 *
 * @param string $hook_suffix The current admin page hook suffix.
 */
add_action( 'admin_enqueue_scripts', 'hebrew_dates_admin_enqueue_styles' );

/**
 * Enqueue widget stylesheet on the dashboard.
 *
 * @since 1.0.0
 * @param string $hook_suffix The current admin page.
 */
function hebrew_dates_admin_enqueue_styles( $hook_suffix ) {
	// Only load on the main dashboard page.
	if ( 'index.php' !== $hook_suffix ) {
		return;
	}

	wp_enqueue_style(
		'hebrew-dates-admin-widget',
		plugin_dir_url( __FILE__ ) . 'assets/css/widget.css',
		array(),
		HEBREW_DATES_ADMIN_VERSION
	);
}

/**
 * Register the dashboard widget.
 *
 * Hooks into 'wp_dashboard_setup' which fires after core dashboard
 * widgets are registered. This is the correct hook for adding
 * custom dashboard widgets.
 */
add_action( 'wp_dashboard_setup', 'hebrew_dates_admin_register_widget' );

/**
 * Register the Hebrew Date Gutenberg block.
 *
 * Uses register_block_type() with the path to the build directory,
 * which contains the compiled block.json, JavaScript, CSS, and render.php.
 * The block metadata (name, attributes, supports) is read from block.json.
 *
 * Hooked to 'init' because block registration must happen during
 * the WordPress initialization phase, before any content is rendered.
 * Unlike the dashboard widget hooks (which only fire on admin pages),
 * this must run on every request so the block renders on the front end
 * and the REST API can serve editor previews via ServerSideRender.
 *
 * @since 1.1.0
 */
add_action( 'init', 'hebrew_dates_admin_register_block' );

/**
 * Register the Hebrew Date block type from compiled build assets.
 *
 * The build directory is generated by `npm run build` using @wordpress/scripts.
 * It contains block.json, compiled JS/CSS, and render.php (copied there
 * by the --webpack-copy-php flag during the build step).
 *
 * Includes a file_exists guard so the plugin degrades gracefully if
 * the build step has not been run — the block simply won't appear
 * in the inserter, but the admin dashboard widget still works.
 *
 * @since 1.1.0
 */
function hebrew_dates_admin_register_block() {
	$block_path = HEBREW_DATES_ADMIN_PATH . 'build/hebrew-date';

	// Only register if the build directory exists (i.e., assets have been compiled).
	if ( file_exists( $block_path . '/block.json' ) ) {
		register_block_type( $block_path );
	}
}

/**
 * Register the Hebrew Date dashboard widget.
 *
 * Uses wp_add_dashboard_widget() to add a widget to the WordPress
 * Admin Dashboard. The widget will appear in the normal dashboard
 * widget area and can be moved/hidden by users.
 *
 * @since 1.0.0
 */
function hebrew_dates_admin_register_widget() {
	wp_add_dashboard_widget(
		'hebrew_dates_admin_widget',                          // Widget ID (unique identifier).
		__( 'Hebrew Date', 'hebrew-dates-admin' ),            // Widget title (translatable).
		'hebrew_dates_admin_display_widget'                   // Display callback function.
	);
}

/**
 * Display the Hebrew Date widget content.
 *
 * This callback function renders the widget's content. It:
 * 1. Fetches the Hebrew date from the Hebcal API (with caching)
 * 2. Displays the date in Hebrew characters (primary)
 * 3. Shows the transliterated version below
 * 4. Lists any Jewish holidays/events for the day
 *
 * All output is properly escaped to prevent XSS vulnerabilities.
 *
 * @since 1.0.0
 */
function hebrew_dates_admin_display_widget() {
	// Instantiate the API client and fetch today's Hebrew date.
	$api    = new Hebcal_API();
	$result = $api->get_hebrew_date();

	// Get the URL to the plugin's assets directory for the icon.
	$icon_url = plugin_dir_url( __FILE__ ) . 'assets/icon.svg';

	// Start widget output.
	echo '<div class="hebrew-date-widget">';

	if ( $result['success'] ) {
		// Main content area: flexbox layout with dates and icon spaced around.
		echo '<div class="hebrew-date-content">';

		// Left side: Date text container (centered within its own space).
		echo '<div class="hebrew-date-text">';

		// Primary display: Hebrew date in Hebrew characters.
		// Using RTL direction for proper Hebrew display.
		printf(
			'<p class="hebrew-date-primary">%s</p>',
			esc_html( $result['hebrew'] )
		);

		// Secondary display: Transliterated Hebrew date.
		// Smaller, muted text for those who prefer Latin characters.
		printf(
			'<p class="hebrew-date-transliterated">%s</p>',
			esc_html( $result['transliterated'] )
		);

		echo '</div>'; // End .hebrew-date-text

		// Right side: Calendar icon.
		printf(
			'<div class="hebrew-date-icon"><img src="%s" alt="%s" /></div>',
			esc_url( $icon_url ),
			esc_attr__( 'Hebrew Calendar', 'hebrew-dates-admin' )
		);

		echo '</div>'; // End .hebrew-date-content

		// Events display: Jewish holidays or special days.
		// Only shown if there are events for today.
		if ( ! empty( $result['events'] ) ) {
			echo '<div class="hebrew-date-events">';

			foreach ( $result['events'] as $event ) {
				printf(
					'<p>%s</p>',
					esc_html( $event )
				);
			}

			echo '</div>';
		}
	} else {
		// Error state: API failed and no cached data available.
		// Display a friendly message instead of breaking the widget.
		printf(
			'<p class="hebrew-date-error">%s</p>',
			esc_html__( 'Unable to load Hebrew date. Please try again later.', 'hebrew-dates-admin' )
		);
	}

	echo '</div>';
}
