<?php
/**
 * Server-side rendering for the Hebrew Date block.
 *
 * Receives $attributes, $content, and $block from WordPress.
 * Calls the existing Hebcal_API class to get fresh Hebrew date data
 * on every page load (the API class handles its own caching via transients).
 *
 * @package Hebrew_Dates_Admin
 * @since   1.1.0
 *
 * @var array    $attributes Block attributes.
 * @var string   $content    Inner block content (empty for this block).
 * @var WP_Block $block      Block instance.
 */

// Prevent direct file access.
if ( ! defined( 'ABSPATH' ) ) {
	exit;
}

// Instantiate the API client and fetch today's Hebrew date.
// Hebcal_API is already loaded via require_once in the main plugin file.
$api    = new Hebcal_API();
$result = $api->get_hebrew_date();

// Extract display attributes with defaults.
$show_events          = $attributes['showEvents'] ?? true;
$show_gregorian_date  = $attributes['showGregorianDate'] ?? false;
$show_transliteration = $attributes['showTransliteration'] ?? true;
$text_alignment       = $attributes['textAlignment'] ?? 'center';

// Build additional CSS classes for text alignment.
// The has-text-align-* classes follow WordPress core convention
// (used by core/paragraph and other blocks for text alignment).
// Allowlist check provides server-side defense in depth — the enum
// in block.json validates on the editor side, but a manipulated post
// could bypass that and inject arbitrary class names.
$allowed_alignments = array( 'left', 'center', 'right' );
$additional_classes = '';
if ( ! empty( $text_alignment ) && in_array( $text_alignment, $allowed_alignments, true ) ) {
	$additional_classes = 'has-text-align-' . $text_alignment;
}

// get_block_wrapper_attributes() merges our custom classes with
// all the classes/styles generated by block supports (typography,
// color, spacing, alignment). This is the standard way to apply
// block support styles in a dynamic render file.
$wrapper_attributes = get_block_wrapper_attributes( array(
	'class' => trim( $additional_classes ),
) );
?>
<div <?php echo $wrapper_attributes; // phpcs:ignore WordPress.Security.EscapeOutput.OutputNotEscaped -- escaped by get_block_wrapper_attributes(). ?>>
	<?php if ( $result['success'] ) : ?>

		<p class="wp-block-hebrew-dates-hebrew-date__hebrew" dir="rtl">
			<?php echo esc_html( $result['hebrew'] ); ?>
		</p>

		<?php if ( $show_transliteration && ! empty( $result['transliterated'] ) ) : ?>
			<p class="wp-block-hebrew-dates-hebrew-date__transliterated">
				<?php echo esc_html( $result['transliterated'] ); ?>
			</p>
		<?php endif; ?>

		<?php if ( $show_gregorian_date ) : ?>
			<p class="wp-block-hebrew-dates-hebrew-date__gregorian">
				<?php
				// Use wp_date() with the site's configured date format
				// and timezone, matching the Gregorian date to the same
				// timezone context as the Hebrew date.
				echo esc_html( wp_date( get_option( 'date_format' ) ) );
				?>
			</p>
		<?php endif; ?>

		<?php if ( $show_events && ! empty( $result['events'] ) ) : ?>
			<div class="wp-block-hebrew-dates-hebrew-date__events">
				<?php foreach ( $result['events'] as $event ) : ?>
					<p class="wp-block-hebrew-dates-hebrew-date__event">
						<?php echo esc_html( $event ); ?>
					</p>
				<?php endforeach; ?>
			</div>
		<?php endif; ?>

	<?php else : ?>

		<p class="wp-block-hebrew-dates-hebrew-date__error">
			<?php esc_html_e( 'Unable to load Hebrew date. Please try again later.', 'hebrew-dates-admin' ); ?>
		</p>

	<?php endif; ?>
</div>
